org.gradle.jvmargs=-Xmx4G
# Base Versions
modid=walkers
artifact_type=release
mod_version=8.3.2
maven_group=dev.tocraft
# Loader Versions
fabric_loader=0.19.3
neoform_version=26.2-2
mixinextras_version=0.5.4
# Upload data
curseforge_id=868922
modrinth_id=Sr1HeD8z
required_dependencies=crafted-core
# Discord Webhook
ping_role=1247931121019261070
# <--- ModMaster --->
minecraft=26.2
supported_versions=26.2
java=25
fabric=0.157.0+26.2
neoforge=26.2.0.59
# Dependencies
craftedcore_version=8.2.1