name: Issue Similarity Check

on:
  issues:
    types: [opened]

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicate issues
        uses: https://github.com/ToCraft/detect-duplicates-action@v1
        with:
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
