name: Release

on:
  push:
    paths:
      - '**.gradle'
      - '**.gradle.kts'
      - '**.properties'
      - '**/src/**'
    branches:
      - "main"
      - "master"
      - "1.**"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: ToCraft/modmaster-release-action@v1.1
        with:
          java-version: '22'
          maven-pass: ${{ secrets.MAVEN_PASS }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          webhook: ${{ secrets.DISCORD_WEB_HOOK }}